"""Create answer quality and regression evaluation tables."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "20260728_0005"
down_revision = "20260728_0004"
branch_labels = None
depends_on = None

J = postgresql.JSONB
T = sa.DateTime(timezone=True)


def upgrade() -> None:
    op.create_table(
        "quality_turns",
        sa.Column("id", sa.Text(), primary_key=True), sa.Column("run_id", sa.Text(), nullable=False, unique=True), sa.Column("conversation_id", sa.Text(), nullable=False), sa.Column("channel", sa.Text(), nullable=False), sa.Column("channel_message_id", sa.Text()), sa.Column("channel_reply_message_id", sa.Text()), sa.Column("user_id", sa.Text()), sa.Column("user_name", sa.Text()), sa.Column("chat_id", sa.Text()), sa.Column("question", sa.Text(), nullable=False), sa.Column("answer", sa.Text()), sa.Column("knowledge_space_id", sa.Text(), nullable=False), sa.Column("domain_id", sa.Text()), sa.Column("status", sa.Text(), nullable=False), sa.Column("provider", sa.Text(), nullable=False), sa.Column("model_name", sa.Text(), nullable=False), sa.Column("last_agent", sa.Text(), nullable=False), sa.Column("application_version", sa.Text(), nullable=False), sa.Column("prompt_version", sa.Text(), nullable=False), sa.Column("duration_ms", sa.Float()), sa.Column("error_type", sa.Text()), sa.Column("feedback_token_hash", sa.Text(), nullable=False), sa.Column("routed_domains_json", J(), nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("specialists_used_json", J(), nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("created_at", T, nullable=False), sa.Column("updated_at", T, nullable=False), sa.Column("completed_at", T),
    )
    op.create_index("ix_quality_turns_conversation", "quality_turns", ["conversation_id", "created_at"])
    op.create_index("ix_quality_turns_channel_message", "quality_turns", ["channel", "channel_message_id"])
    op.create_table("quality_citations", sa.Column("id", sa.Text(), primary_key=True), sa.Column("turn_id", sa.Text(), sa.ForeignKey("quality_turns.id", ondelete="CASCADE"), nullable=False), sa.Column("sequence", sa.Integer(), nullable=False), sa.Column("source_type", sa.Text(), nullable=False), sa.Column("source_id", sa.Text(), nullable=False), sa.Column("title", sa.Text(), nullable=False), sa.Column("domain", sa.Text(), nullable=False), sa.Column("metadata_json", J(), nullable=False), sa.UniqueConstraint("turn_id", "sequence", name="uq_quality_citation_sequence"))
    op.create_table("quality_tool_runs", sa.Column("id", sa.Text(), primary_key=True), sa.Column("turn_id", sa.Text(), sa.ForeignKey("quality_turns.id", ondelete="CASCADE"), nullable=False), sa.Column("sequence", sa.Integer(), nullable=False), sa.Column("tool_call_id", sa.Text(), nullable=False), sa.Column("tool_name", sa.Text(), nullable=False), sa.Column("agent_name", sa.Text(), nullable=False), sa.Column("status", sa.Text(), nullable=False), sa.Column("duration_ms", sa.Float()), sa.Column("arguments_json", J(), nullable=False))
    op.create_table("quality_feedback", sa.Column("id", sa.Text(), primary_key=True), sa.Column("turn_id", sa.Text(), sa.ForeignKey("quality_turns.id", ondelete="CASCADE"), nullable=False), sa.Column("channel", sa.Text(), nullable=False), sa.Column("feedback_key", sa.Text(), nullable=False), sa.Column("user_id", sa.Text()), sa.Column("user_name", sa.Text()), sa.Column("rating", sa.Text(), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("reason_code", sa.Text(), nullable=False), sa.Column("created_at", T, nullable=False), sa.Column("updated_at", T, nullable=False), sa.UniqueConstraint("turn_id", "channel", "feedback_key", name="uq_quality_feedback_turn_channel_key"))
    op.create_index("ix_quality_feedback_rating", "quality_feedback", ["rating"])
    op.create_table("quality_spans", sa.Column("id", sa.Text(), primary_key=True), sa.Column("turn_id", sa.Text(), sa.ForeignKey("quality_turns.id", ondelete="CASCADE"), nullable=False), sa.Column("run_id", sa.Text(), nullable=False), sa.Column("kind", sa.Text(), nullable=False), sa.Column("name", sa.Text(), nullable=False), sa.Column("status", sa.Text(), nullable=False), sa.Column("duration_ms", sa.Float()), sa.Column("input_tokens", sa.Integer(), nullable=False), sa.Column("output_tokens", sa.Integer(), nullable=False), sa.Column("total_tokens", sa.Integer(), nullable=False), sa.Column("metadata_json", J(), nullable=False), sa.Column("created_at", T, nullable=False))
    op.create_table("quality_annotations", sa.Column("id", sa.Text(), primary_key=True), sa.Column("turn_id", sa.Text(), sa.ForeignKey("quality_turns.id", ondelete="CASCADE"), nullable=False), sa.Column("source", sa.Text(), nullable=False), sa.Column("code", sa.Text(), nullable=False), sa.Column("severity", sa.Text(), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("details_json", J(), nullable=False), sa.Column("review_status", sa.Text(), nullable=False), sa.Column("reviewer", sa.Text()), sa.Column("reviewed_at", T), sa.Column("created_at", T, nullable=False), sa.Column("updated_at", T, nullable=False))
    op.create_table(
        "eval_cases",
        sa.Column("id", sa.Text(), primary_key=True), sa.Column("source_turn_id", sa.Text()), sa.Column("name", sa.Text(), nullable=False), sa.Column("question", sa.Text(), nullable=False), sa.Column("knowledge_space_id", sa.Text(), nullable=False), sa.Column("domain_id", sa.Text()), sa.Column("required_tools_json", J(), nullable=False), sa.Column("required_citation_types_json", J(), nullable=False), sa.Column("required_facts_json", J(), nullable=False), sa.Column("forbidden_facts_json", J(), nullable=False), sa.Column("tags_json", J(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("expected_behavior", sa.Text(), nullable=False), sa.Column("max_latency_ms", sa.Float(), nullable=False), sa.Column("max_tool_calls", sa.Integer(), nullable=False), sa.Column("max_citations", sa.Integer(), nullable=False), sa.Column("turns_json", J(), nullable=False), sa.Column("task_type", sa.Text(), nullable=False), sa.Column("suite", sa.Text(), nullable=False), sa.Column("priority", sa.Text(), nullable=False), sa.Column("approval_state", sa.Text(), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("created_at", T, nullable=False), sa.Column("updated_at", T, nullable=False),
    )
    op.create_table("eval_runs", sa.Column("id", sa.Text(), primary_key=True), sa.Column("status", sa.Text(), nullable=False), sa.Column("application_version", sa.Text(), nullable=False), sa.Column("provider", sa.Text(), nullable=False), sa.Column("model_name", sa.Text(), nullable=False), sa.Column("total_cases", sa.Integer(), nullable=False), sa.Column("passed_cases", sa.Integer(), nullable=False), sa.Column("failed_cases", sa.Integer(), nullable=False), sa.Column("case_ids_json", J(), nullable=False), sa.Column("config_snapshot_json", J(), nullable=False), sa.Column("cancel_requested", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("current_case", sa.Integer(), nullable=False), sa.Column("created_at", T, nullable=False), sa.Column("updated_at", T), sa.Column("completed_at", T))
    op.create_index("ix_eval_runs_claim", "eval_runs", ["status", "created_at"])
    op.create_table("eval_results", sa.Column("id", sa.Text(), primary_key=True), sa.Column("run_id", sa.Text(), sa.ForeignKey("eval_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("case_id", sa.Text(), nullable=False), sa.Column("status", sa.Text(), nullable=False), sa.Column("answer", sa.Text()), sa.Column("last_agent", sa.Text(), nullable=False), sa.Column("tool_names_json", J(), nullable=False), sa.Column("citation_types_json", J(), nullable=False), sa.Column("duration_ms", sa.Float()), sa.Column("checks_json", J(), nullable=False), sa.Column("passed", sa.Boolean(), nullable=False), sa.Column("error_type", sa.Text()), sa.Column("judge_score", sa.Float()), sa.Column("judge_json", J(), nullable=False), sa.Column("failure_codes_json", J(), nullable=False), sa.Column("review_state", sa.Text(), nullable=False), sa.Column("case_snapshot_json", J(), nullable=False), sa.Column("created_at", T, nullable=False), sa.UniqueConstraint("run_id", "case_id", name="uq_eval_result_run_case"))


def downgrade() -> None:
    for table in ("eval_results", "eval_runs", "eval_cases", "quality_annotations", "quality_spans", "quality_feedback", "quality_tool_runs", "quality_citations", "quality_turns"):
        op.drop_table(table)
